apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: ${GRAFANA_POSTGRES_URL}
    database: ${GRAFANA_POSTGRES_DB}
    user: ${GRAFANA_POSTGRES_USER}
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      timescaledb: false
    isDefault: true
    editable: false
